language: erlang
otp_release:
  - 20.3
  - 21.0
before_script:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz 
  - tar xzf libsodium-1.0.16.tar.gz 
  - cd libsodium-1.0.16  
  - ./configure --prefix=/usr && make && make install
  - cd ..

script:
  - rebar3 proper
